//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Err {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Err() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Err", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Site settings error 的本地化字符串。
        /// </summary>
        internal static string ERR_CONFIG_INVALID {
            get {
                return ResourceManager.GetString("ERR_CONFIG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database error 的本地化字符串。
        /// </summary>
        internal static string ERR_DBERROR {
            get {
                return ResourceManager.GetString("ERR_DBERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use this userid 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINID_CANNOTUSE {
            get {
                return ResourceManager.GetString("ERR_LOGINID_CANNOTUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Userid must have be 4~10 letters 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINID_FORMAT {
            get {
                return ResourceManager.GetString("ERR_LOGINID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input userid 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINID_INPUT {
            get {
                return ResourceManager.GetString("ERR_LOGINID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The userid has been already using 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINID_INUSED {
            get {
                return ResourceManager.GetString("ERR_LOGINID_INUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The userid doesnot exist 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINID_INVALID {
            get {
                return ResourceManager.GetString("ERR_LOGINID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong password 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINPWDCONF_FORMAT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWDCONF_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input confirm password 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINPWDCONF_INPUT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWDCONF_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password must be 4~50 letters 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINPWD_FORMAT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password must be 4~50 letters 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINPWD_FORMAT1 {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_FORMAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINPWD_INPUT {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGINPWD_INPUT1 {
            get {
                return ResourceManager.GetString("ERR_LOGINPWD_INPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Userid or password is wrong 的本地化字符串。
        /// </summary>
        internal static string ERR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot use this nickname 的本地化字符串。
        /// </summary>
        internal static string ERR_NICKNAME_CANNOTUSE {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_CANNOTUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nichname must be 3~10 letters 的本地化字符串。
        /// </summary>
        internal static string ERR_NICKNAME_FORMAT {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input nickname 的本地化字符串。
        /// </summary>
        internal static string ERR_NICKNAME_INPUT {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nickname already used 的本地化字符串。
        /// </summary>
        internal static string ERR_NICKNAME_INUSED {
            get {
                return ResourceManager.GetString("ERR_NICKNAME_INUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpermitted user 的本地化字符串。
        /// </summary>
        internal static string ERR_REQUIRED_ADMINAUTH {
            get {
                return ResourceManager.GetString("ERR_REQUIRED_ADMINAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please login 的本地化字符串。
        /// </summary>
        internal static string ERR_REQUIRED_AUTH {
            get {
                return ResourceManager.GetString("ERR_REQUIRED_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact must be XXX-XXXX-XXXX or XXXXXXXXXXX format 的本地化字符串。
        /// </summary>
        internal static string ERR_TELNO_FORMAT {
            get {
                return ResourceManager.GetString("ERR_TELNO_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input contact 的本地化字符串。
        /// </summary>
        internal static string ERR_TELNO_INPUT {
            get {
                return ResourceManager.GetString("ERR_TELNO_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block \n dateime: {0} 的本地化字符串。
        /// </summary>
        internal static string ERR_USER_INTERCEPT {
            get {
                return ResourceManager.GetString("ERR_USER_INTERCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your data was deleted.\ndatatime: {0} 的本地化字符串。
        /// </summary>
        internal static string ERR_USER_LEAVE {
            get {
                return ResourceManager.GetString("ERR_USER_LEAVE", resourceCulture);
            }
        }
    }
}
