//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Msg", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already logined from ip {0}.
        /// </summary>
        internal static string MSG_ALEADYLOGIN {
            get {
                return ResourceManager.GetString("MSG_ALEADYLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An excessive number of API request. You must buy new product..
        /// </summary>
        internal static string MSG_APIREQUESTOVER {
            get {
                return ResourceManager.GetString("MSG_APIREQUESTOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You loged out. Please login again..
        /// </summary>
        internal static string MSG_AUTO_LOGOUT {
            get {
                return ResourceManager.GetString("MSG_AUTO_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An excessive size of hardware. You must delete some VIs or but new product..
        /// </summary>
        internal static string MSG_HARDOVER {
            get {
                return ResourceManager.GetString("MSG_HARDOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An excessive number of markers. You must buy new product..
        /// </summary>
        internal static string MSG_MARKEROVER {
            get {
                return ResourceManager.GetString("MSG_MARKEROVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member was added..
        /// </summary>
        internal static string MSG_MEMBERJOIN {
            get {
                return ResourceManager.GetString("MSG_MEMBERJOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member information changed..
        /// </summary>
        internal static string MSG_MEMBERMODIFIED {
            get {
                return ResourceManager.GetString("MSG_MEMBERMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product information changed..
        /// </summary>
        internal static string MSG_MODPRODUCT {
            get {
                return ResourceManager.GetString("MSG_MODPRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select item that you want to delete..
        /// </summary>
        internal static string MSG_NOSELECTITEM {
            get {
                return ResourceManager.GetString("MSG_NOSELECTITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notice changed..
        /// </summary>
        internal static string MSG_NOTICEMODIFIED {
            get {
                return ResourceManager.GetString("MSG_NOTICEMODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notice registered..
        /// </summary>
        internal static string MSG_NOTICEREGISTERED {
            get {
                return ResourceManager.GetString("MSG_NOTICEREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was added..
        /// </summary>
        internal static string MSG_PRODUCTREGISTERD {
            get {
                return ResourceManager.GetString("MSG_PRODUCTREGISTERD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member information was deleted..
        /// </summary>
        internal static string MSG_REMOVEUSEROK {
            get {
                return ResourceManager.GetString("MSG_REMOVEUSEROK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An excessive size of traffic. You must buy new product..
        /// </summary>
        internal static string MSG_TRAFFICOVER {
            get {
                return ResourceManager.GetString("MSG_TRAFFICOVER", resourceCulture);
            }
        }
    }
}
